import { useEffect, useMemo, useState } from 'react'
import { supabase } from './lib/supabase'
import { BarChart3, Boxes, Calculator, CircleDollarSign, ClipboardList, Cog, Gauge, LogOut, Menu, PackagePlus, Plus, Printer, ReceiptText, Search, ShieldCheck, ShoppingCart, Smartphone, Users, Wallet, Wrench, X } from 'lucide-react'

const money=(n=0)=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(n)||0)
const fmtDate=d=>new Intl.DateTimeFormat('es-CO',{dateStyle:'medium',timeStyle:'short'}).format(new Date(d))

function Brand(){return <div className="brand"><img src="/logo-electresid.svg" alt="Electresid"/><div><b>Electresid</b><span>POS & Servicio técnico</span></div></div>}

function Login(){
  const[mode,setMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
  const submit=async e=>{e.preventDefault();setBusy(true);setMsg('');const{error}=mode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{data:{nombre:name}}});if(error)setMsg(error.message);else if(mode==='signup')setMsg('Usuario creado. Si Supabase solicita confirmación, revisa el correo.');setBusy(false)}
  return <main className="auth-shell"><section className="auth-card"><Brand/><div className="bolt">⚡</div><h1>{mode==='login'?'Ingreso al sistema':'Crear primer usuario'}</h1><p>Ventas, inventario y reparaciones en una sola pantalla.</p><form onSubmit={submit}>{mode==='signup'&&<label>Nombre<input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label>Correo<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Contraseña<input type="password" minLength="6" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button disabled={busy}>{busy?'Procesando...':mode==='login'?'Entrar':'Crear usuario'}</button></form>{msg&&<div className="notice">{msg}</div>}<button className="link-btn" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'¿Primera vez? Crear usuario':'Ya tengo usuario'}</button><small>El primer usuario registrado queda como administrador.</small></section></main>
}

const sections=[['dashboard','Resumen',Gauge],['pos','Punto de venta',ShoppingCart],['productos','Productos',Boxes],['inventario','Inventario',PackagePlus],['reparaciones','Reparaciones',Wrench],['clientes','Clientes',Users],['caja','Caja',Wallet],['gastos','Gastos',CircleDollarSign],['reportes','Reportes',BarChart3],['config','Configuración',Cog]]

export default function App(){
  const[session,setSession]=useState(null),[profile,setProfile]=useState(null),[section,setSection]=useState('dashboard'),[menu,setMenu]=useState(false)
  useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[])
  useEffect(()=>{if(!session)return;supabase.from('perfiles').select('*').eq('id',session.user.id).single().then(({data})=>setProfile(data))},[session])
  if(!session)return <Login/>
  const Current={dashboard:Dashboard,pos:POS,productos:Productos,inventario:Inventario,reparaciones:Reparaciones,clientes:Clientes,caja:Caja,gastos:Gastos,reportes:Reportes,config:Config}[section]
  return <div className="app-shell"><aside className={menu?'sidebar open':'sidebar'}><Brand/><nav>{sections.map(([id,label,Icon])=><button key={id} className={section===id?'active':''} onClick={()=>{setSection(id);setMenu(false)}}><Icon size={19}/><span>{label}</span></button>)}</nav><div className="userbox"><ShieldCheck size={18}/><div><b>{profile?.nombre||session.user.email}</b><span>{profile?.rol||'usuario'}</span></div></div><button className="logout" onClick={()=>supabase.auth.signOut()}><LogOut size={18}/>Salir</button></aside><main className="content"><header className="topbar"><button className="menu-btn" onClick={()=>setMenu(!menu)}><Menu/></button><div><h1>{sections.find(x=>x[0]===section)?.[1]}</h1><span>Electresid · celulares, computadores y consolas</span></div></header><Current profile={profile}/></main></div>
}

function Stat({label,value,icon:Icon,sub}){return <div className="stat"><div className="stat-icon"><Icon/></div><div><span>{label}</span><b>{value}</b>{sub&&<small>{sub}</small>}</div></div>}
function Table({headers,rows}){return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>):<tr><td colSpan={headers.length} className="empty">Sin registros todavía.</td></tr>}</tbody></table></div>}

function Dashboard(){
  const[data,setData]=useState({ventas:0,ingresos:0,stock:0,reparaciones:0,bajo:[]})
  useEffect(()=>{(async()=>{const today=new Date();today.setHours(0,0,0,0);const[{data:v},{data:s},{data:r},{data:b}]=await Promise.all([supabase.from('ventas').select('total').gte('created_at',today.toISOString()).eq('estado','completada'),supabase.from('stock_actual').select('stock'),supabase.from('reparaciones').select('id').not('estado','in','("entregado","cancelado")'),supabase.from('productos_stock_bajo').select('*').limit(8)]);setData({ventas:v?.length||0,ingresos:(v||[]).reduce((a,x)=>a+Number(x.total),0),stock:(s||[]).reduce((a,x)=>a+Number(x.stock),0),reparaciones:r?.length||0,bajo:b||[]})})()},[])
  return <><div className="stats"><Stat label="Ventas hoy" value={data.ventas} icon={ReceiptText}/><Stat label="Ingresos hoy" value={money(data.ingresos)} icon={CircleDollarSign}/><Stat label="Unidades en stock" value={data.stock} icon={Boxes}/><Stat label="Reparaciones abiertas" value={data.reparaciones} icon={Wrench}/></div><section className="panel"><div className="panel-head"><div><h2>Stock bajo</h2><p>Productos que requieren atención.</p></div></div><Table headers={['Producto','Variante','SKU','Stock','Mínimo']} rows={data.bajo.map(x=>[x.producto,x.variante||'—',x.sku,x.stock,x.stock_minimo])}/></section></>
}

function POS(){
  const[q,setQ]=useState(''),[items,setItems]=useState([]),[cart,setCart]=useState([]),[client,setClient]=useState(null),[clients,setClients]=useState([]),[pay,setPay]=useState('efectivo'),[busy,setBusy]=useState(false),[lastSale,setLastSale]=useState(null)
  const loadProducts=async()=>{const{data}=await supabase.from('variantes').select('id,sku,codigo_barras,nombre,precio_venta,producto:productos(nombre),stock:stock_actual(stock)').eq('activo',true).limit(500);setItems(data||[])}
  useEffect(()=>{loadProducts();supabase.from('clientes').select('id,nombre,documento').order('nombre').limit(200).then(({data})=>setClients(data||[]))},[])
  const filtered=useMemo(()=>{const s=q.toLowerCase();return items.filter(x=>!s||x.sku.toLowerCase().includes(s)||(x.codigo_barras||'').includes(s)||(x.producto?.nombre||'').toLowerCase().includes(s)||(x.nombre||'').toLowerCase().includes(s)).slice(0,50)},[items,q])
  const add=x=>setCart(c=>{const i=c.find(y=>y.id===x.id);return i?c.map(y=>y.id===x.id?{...y,qty:y.qty+1}:y):[...c,{...x,qty:1}]})
  const total=cart.reduce((a,x)=>a+Number(x.precio_venta)*x.qty,0)
  const sale=async()=>{if(!cart.length)return;setBusy(true);const{data,error}=await supabase.rpc('registrar_venta',{p_items:cart.map(x=>({variante_id:x.id,cantidad:x.qty})),p_pagos:[{metodo:pay,valor:total}],p_cliente_id:client||null,p_caja_id:null,p_descuento:0,p_observacion:null});if(error)alert(error.message);else{const{data:v}=await supabase.from('ventas').select('*,cliente:clientes(*),detalle_ventas(*),pagos_venta(*)').eq('id',data).single();setLastSale(v);setCart([]);await loadProducts()}setBusy(false)}
  return <div className="pos-grid"><section className="panel"><div className="search"><Search size={19}/><input placeholder="Buscar por nombre, SKU o código de barras..." value={q} onChange={e=>setQ(e.target.value)} autoFocus/></div><div className="product-grid">{filtered.map(x=><button className="product-card" key={x.id} onClick={()=>add(x)}><Smartphone/><b>{x.producto?.nombre}</b><span>{x.nombre||x.sku}</span><small>Stock: {x.stock?.[0]?.stock??0}</small><strong>{money(x.precio_venta)}</strong></button>)}</div></section><section className="panel cart"><div className="panel-head"><h2>Venta actual</h2><span className="pill">{cart.reduce((a,x)=>a+x.qty,0)} ítems</span></div><select value={client||''} onChange={e=>setClient(e.target.value||null)}><option value="">Consumidor final</option>{clients.map(c=><option value={c.id} key={c.id}>{c.nombre} {c.documento?`· ${c.documento}`:''}</option>)}</select><div className="cart-list">{cart.map(x=><div className="cart-row" key={x.id}><div><b>{x.producto?.nombre}</b><span>{x.nombre||x.sku}</span></div><input type="number" min="1" value={x.qty} onChange={e=>setCart(c=>c.map(y=>y.id===x.id?{...y,qty:+e.target.value}:y))}/><strong>{money(x.precio_venta*x.qty)}</strong><button onClick={()=>setCart(c=>c.filter(y=>y.id!==x.id))}><X size={16}/></button></div>)}</div><div className="total"><span>Total</span><b>{money(total)}</b></div><select value={pay} onChange={e=>setPay(e.target.value)}><option value="efectivo">Efectivo</option><option value="tarjeta">Tarjeta</option><option value="transferencia">Transferencia</option><option value="nequi">Nequi</option><option value="daviplata">Daviplata</option><option value="otro">Otro</option></select><button className="primary" disabled={!cart.length||busy} onClick={sale}><Calculator/> {busy?'Registrando...':'Cobrar venta'}</button>{lastSale&&<button className="secondary" onClick={()=>printTicket(lastSale)}><Printer/>Imprimir factura 80 mm</button>}</section></div>
}

function printTicket(sale){const win=window.open('','ticket','width=430,height=720');if(!win)return;const rows=(sale.detalle_ventas||[]).map(i=>`<tr><td>${i.descripcion}<br><small>${i.cantidad} x ${money(i.precio_unitario)}</small></td><td>${money(i.subtotal)}</td></tr>`).join('');win.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Factura ${sale.numero}</title><style>@page{size:80mm auto;margin:3mm}*{box-sizing:border-box}body{width:74mm;margin:0 auto;font-family:Arial,sans-serif;color:#000;font-size:11px}h1{font-family:Georgia,serif;font-style:italic;font-size:24px;margin:0}header{text-align:center;border-bottom:1px dashed #000;padding-bottom:7px}table{width:100%;border-collapse:collapse;margin:8px 0}td{padding:5px 0;vertical-align:top;border-bottom:1px dotted #bbb}td:last-child{text-align:right;font-weight:700}.tot{font-size:16px;text-align:right;border-top:2px solid #000;padding-top:8px}.meta{margin:8px 0}.foot{text-align:center;border-top:1px dashed #000;padding-top:8px}.bolt{font-size:20px}</style></head><body><header><div class="bolt">⚡</div><h1>Electresid</h1><b>SERVICIO TÉCNICO</b><div>CELULARES · COMPUTADORES · CONSOLAS</div></header><div class="meta"><b>Factura interna #${sale.numero}</b><br>${fmtDate(sale.created_at)}<br>${sale.cliente?`Cliente: ${sale.cliente.nombre}`:'Consumidor final'}</div><table>${rows}</table><div class="tot">TOTAL: ${money(sale.total)}</div><p>Pago: ${(sale.pagos_venta||[]).map(p=>`${p.metodo}: ${money(p.valor)}`).join(' + ')}</p><div class="foot">Gracias por confiar en Electresid.<br>Documento interno de venta · No es factura electrónica.</div><script>window.onload=()=>window.print()<\/script></body></html>`);win.document.close()}

function Productos(){
  const[rows,setRows]=useState([]),[cats,setCats]=useState([]),[show,setShow]=useState(false),[form,setForm]=useState({nombre:'',categoria_id:'',sku:'',precio_venta:'',costo:'',stock_minimo:1})
  const load=async()=>{const{data}=await supabase.from('variantes').select('id,sku,codigo_barras,nombre,precio_venta,costo,stock_minimo,producto:productos(id,nombre,categoria:categorias(nombre)),stock:stock_actual(stock)').order('created_at',{ascending:false});setRows(data||[])}
  useEffect(()=>{load();supabase.from('categorias').select('*').eq('activo',true).order('nombre').then(({data})=>setCats(data||[]))},[])
  const save=async()=>{const{data:p,error:e}=await supabase.from('productos').insert({nombre:form.nombre,categoria_id:form.categoria_id}).select().single();if(e)return alert(e.message);const{error}=await supabase.from('variantes').insert({producto_id:p.id,sku:form.sku,precio_venta:+form.precio_venta,costo:+form.costo||0,stock_minimo:+form.stock_minimo});if(error)alert(error.message);else{setShow(false);setForm({nombre:'',categoria_id:'',sku:'',precio_venta:'',costo:'',stock_minimo:1});load()}}
  return <section className="panel"><div className="panel-head"><div><h2>Catálogo de productos</h2><p>SKU, costos, precios y stock mínimo.</p></div><button className="primary compact" onClick={()=>setShow(!show)}><Plus/>Nuevo producto</button></div>{show&&<div className="form-grid"><input placeholder="Nombre" value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/><select value={form.categoria_id} onChange={e=>setForm({...form,categoria_id:e.target.value})}><option value="">Categoría</option>{cats.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select><input placeholder="SKU" value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/><input type="number" placeholder="Costo" value={form.costo} onChange={e=>setForm({...form,costo:e.target.value})}/><input type="number" placeholder="Precio venta" value={form.precio_venta} onChange={e=>setForm({...form,precio_venta:e.target.value})}/><input type="number" placeholder="Stock mínimo" value={form.stock_minimo} onChange={e=>setForm({...form,stock_minimo:e.target.value})}/><button className="primary" onClick={save}>Guardar</button></div>}<Table headers={['Producto','Categoría','SKU','Costo','Precio','Stock','Mínimo']} rows={rows.map(x=>[x.producto?.nombre,x.producto?.categoria?.nombre,x.sku,money(x.costo),money(x.precio_venta),x.stock?.[0]?.stock??0,x.stock_minimo])}/></section>
}

function Inventario(){
  const[rows,setRows]=useState([]),[sel,setSel]=useState(''),[qty,setQty]=useState(1),[entrada,setEntrada]=useState(true),[note,setNote]=useState('')
  const load=()=>supabase.from('variantes').select('id,sku,nombre,producto:productos(nombre),stock:stock_actual(stock)').eq('activo',true).order('sku').then(({data})=>setRows(data||[]));useEffect(load,[])
  const adjust=async()=>{const{error}=await supabase.rpc('ajustar_inventario',{p_variante_id:sel,p_cantidad:+qty,p_es_entrada:entrada,p_observacion:note||null,p_costo_unitario:null});if(error)alert(error.message);else{setQty(1);setNote('');load()}}
  return <><section className="panel"><div className="panel-head"><div><h2>Ajuste de inventario</h2><p>Registra entradas, conteos, daños o salidas manuales.</p></div></div><div className="form-grid"><select value={sel} onChange={e=>setSel(e.target.value)}><option value="">Selecciona producto</option>{rows.map(x=><option value={x.id} key={x.id}>{x.sku} · {x.producto?.nombre} · stock {x.stock?.[0]?.stock??0}</option>)}</select><select value={entrada?'in':'out'} onChange={e=>setEntrada(e.target.value==='in')}><option value="in">Entrada</option><option value="out">Salida</option></select><input type="number" min="0.01" step="0.01" value={qty} onChange={e=>setQty(e.target.value)}/><input placeholder="Observación" value={note} onChange={e=>setNote(e.target.value)}/><button className="primary" onClick={adjust} disabled={!sel}>Registrar</button></div></section><section className="panel"><Table headers={['SKU','Producto','Variante','Stock actual']} rows={rows.map(x=>[x.sku,x.producto?.nombre,x.nombre||'—',x.stock?.[0]?.stock??0])}/></section></>
}

function Reparaciones(){
  const[rows,setRows]=useState([]),[clients,setClients]=useState([]),[show,setShow]=useState(false),[f,setF]=useState({cliente_id:'',equipo:'Celular',marca:'',modelo:'',problema_reportado:'',imei_serial:''})
  const load=()=>supabase.from('reparaciones').select('*,cliente:clientes(nombre,telefono)').order('fecha_ingreso',{ascending:false}).then(({data})=>setRows(data||[]));useEffect(()=>{load();supabase.from('clientes').select('id,nombre').order('nombre').then(({data})=>setClients(data||[]))},[])
  const save=async()=>{const{error}=await supabase.from('reparaciones').insert(f);if(error)alert(error.message);else{setShow(false);load()}};const state=async(id,estado)=>{await supabase.from('reparaciones').update({estado}).eq('id',id);load()}
  return <section className="panel"><div className="panel-head"><div><h2>Órdenes de reparación</h2><p>Recepción, diagnóstico, reparación y entrega.</p></div><button className="primary compact" onClick={()=>setShow(!show)}><Plus/>Nueva orden</button></div>{show&&<div className="form-grid"><select value={f.cliente_id} onChange={e=>setF({...f,cliente_id:e.target.value})}><option value="">Cliente</option>{clients.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select><input placeholder="Equipo" value={f.equipo} onChange={e=>setF({...f,equipo:e.target.value})}/><input placeholder="Marca" value={f.marca} onChange={e=>setF({...f,marca:e.target.value})}/><input placeholder="Modelo" value={f.modelo} onChange={e=>setF({...f,modelo:e.target.value})}/><input placeholder="IMEI / serial" value={f.imei_serial} onChange={e=>setF({...f,imei_serial:e.target.value})}/><input placeholder="Problema reportado" value={f.problema_reportado} onChange={e=>setF({...f,problema_reportado:e.target.value})}/><button className="primary" onClick={save}>Crear orden</button></div>}<div className="repair-list">{rows.map(r=><article className="repair-card" key={r.id}><div><span className="pill">#{r.numero}</span><h3>{r.equipo} {r.marca} {r.modelo}</h3><p>{r.cliente?.nombre} · {r.problema_reportado}</p><small>{fmtDate(r.fecha_ingreso)}</small></div><select value={r.estado} onChange={e=>state(r.id,e.target.value)}>{['recibido','diagnostico','esperando_aprobacion','en_reparacion','esperando_repuesto','terminado','entregado','cancelado'].map(s=><option key={s}>{s}</option>)}</select></article>)}</div></section>
}

function Clientes(){
  const[rows,setRows]=useState([]),[f,setF]=useState({nombre:'',documento:'',telefono:'',email:''});const load=()=>supabase.from('clientes').select('*').order('created_at',{ascending:false}).then(({data})=>setRows(data||[]));useEffect(load,[]);const save=async()=>{const{error}=await supabase.from('clientes').insert(f);if(error)alert(error.message);else{setF({nombre:'',documento:'',telefono:'',email:''});load()}}
  return <section className="panel"><div className="panel-head"><div><h2>Clientes</h2><p>Historial comercial y soporte técnico.</p></div></div><div className="form-grid"><input placeholder="Nombre" value={f.nombre} onChange={e=>setF({...f,nombre:e.target.value})}/><input placeholder="Documento" value={f.documento} onChange={e=>setF({...f,documento:e.target.value})}/><input placeholder="Teléfono" value={f.telefono} onChange={e=>setF({...f,telefono:e.target.value})}/><input placeholder="Correo" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><button className="primary" onClick={save}>Agregar</button></div><Table headers={['Nombre','Documento','Teléfono','Correo']} rows={rows.map(x=>[x.nombre,x.documento||'—',x.telefono||'—',x.email||'—'])}/></section>
}

function Caja({profile}){
  const[open,setOpen]=useState(null),[initial,setInitial]=useState(0),[declared,setDeclared]=useState(0),[moves,setMoves]=useState([]);const load=async()=>{const{data}=await supabase.from('cajas').select('*').eq('estado','abierta').order('fecha_apertura',{ascending:false}).limit(1).maybeSingle();setOpen(data);if(data){const{data:m}=await supabase.from('movimientos_caja').select('*').eq('caja_id',data.id).order('created_at',{ascending:false});setMoves(m||[])}};useEffect(()=>{load()},[]);const start=async()=>{const{error}=await supabase.from('cajas').insert({saldo_inicial:+initial,usuario_apertura:profile.id});if(error)alert(error.message);else load()};const close=async()=>{await supabase.from('cajas').update({estado:'cerrada',fecha_cierre:new Date().toISOString(),saldo_final_declarado:+declared,usuario_cierre:profile.id}).eq('id',open.id);load()}
  return <><section className="panel">{!open?<><h2>Abrir caja</h2><div className="form-grid"><input type="number" value={initial} onChange={e=>setInitial(e.target.value)} placeholder="Saldo inicial"/><button className="primary" onClick={start}>Abrir caja</button></div></>:<><div className="panel-head"><div><h2>Caja abierta</h2><p>Desde {fmtDate(open.fecha_apertura)}</p></div><span className="pill success">Activa</span></div><div className="stats"><Stat label="Saldo inicial" value={money(open.saldo_inicial)} icon={Wallet}/><Stat label="Movimientos" value={moves.length} icon={ClipboardList}/></div><div className="form-grid"><input type="number" value={declared} onChange={e=>setDeclared(e.target.value)} placeholder="Efectivo contado"/><button className="danger" onClick={close}>Cerrar caja</button></div></>}</section>{open&&<section className="panel"><Table headers={['Fecha','Tipo','Método','Descripción','Valor']} rows={moves.map(x=>[fmtDate(x.created_at),x.tipo,x.metodo,x.descripcion||'—',money(x.valor)])}/></section>}</>
}

function Gastos({profile}){
  const[rows,setRows]=useState([]),[f,setF]=useState({categoria:'Servicios',descripcion:'',valor:'',metodo:'efectivo'});const load=()=>supabase.from('gastos').select('*').order('created_at',{ascending:false}).limit(100).then(({data})=>setRows(data||[]));useEffect(load,[]);const save=async()=>{const{error}=await supabase.from('gastos').insert({...f,valor:+f.valor,usuario_id:profile.id});if(error)alert(error.message);else{setF({...f,descripcion:'',valor:''});load()}}
  return <section className="panel"><div className="panel-head"><div><h2>Gastos</h2><p>Control de egresos del negocio.</p></div></div><div className="form-grid"><input value={f.categoria} onChange={e=>setF({...f,categoria:e.target.value})} placeholder="Categoría"/><input value={f.descripcion} onChange={e=>setF({...f,descripcion:e.target.value})} placeholder="Descripción"/><input type="number" value={f.valor} onChange={e=>setF({...f,valor:e.target.value})} placeholder="Valor"/><select value={f.metodo} onChange={e=>setF({...f,metodo:e.target.value})}><option>efectivo</option><option>tarjeta</option><option>transferencia</option><option>nequi</option><option>daviplata</option><option>otro</option></select><button className="primary" onClick={save}>Registrar gasto</button></div><Table headers={['Fecha','Categoría','Descripción','Método','Valor']} rows={rows.map(x=>[fmtDate(x.created_at),x.categoria,x.descripcion,x.metodo,money(x.valor)])}/></section>
}

function Reportes(){
  const[daily,setDaily]=useState([]),[prod,setProd]=useState([]);useEffect(()=>{supabase.from('reporte_ventas_diarias').select('*').order('fecha',{ascending:false}).limit(30).then(({data})=>setDaily(data||[]));supabase.from('reporte_productos_vendidos').select('*').order('ventas',{ascending:false}).limit(20).then(({data})=>setProd(data||[]))},[]);const sum=daily.reduce((a,x)=>a+Number(x.ventas||0),0),util=daily.reduce((a,x)=>a+Number(x.utilidad_bruta||0),0)
  return <><div className="stats"><Stat label="Ventas 30 días" value={money(sum)} icon={CircleDollarSign}/><Stat label="Utilidad bruta" value={money(util)} icon={BarChart3}/><Stat label="Transacciones" value={daily.reduce((a,x)=>a+Number(x.cantidad_ventas||0),0)} icon={ReceiptText}/></div><section className="panel"><h2>Ventas por día</h2><Table headers={['Fecha','Ventas','Transacciones','Utilidad bruta']} rows={daily.map(x=>[x.fecha,money(x.ventas),x.cantidad_ventas,money(x.utilidad_bruta)])}/></section><section className="panel"><h2>Productos más vendidos</h2><Table headers={['Producto','Variante','SKU','Unidades','Ventas','Utilidad']} rows={prod.map(x=>[x.producto,x.variante||'—',x.sku,x.unidades,money(x.ventas),money(x.utilidad_bruta)])}/></section></>
}

function Config({profile}){
  const[f,setF]=useState(null);useEffect(()=>{supabase.from('configuracion_negocio').select('*').limit(1).single().then(({data})=>setF(data))},[]);if(!f)return <section className="panel">Cargando...</section>;const save=async()=>{const{error}=await supabase.from('configuracion_negocio').update(f).eq('id',f.id);alert(error?error.message:'Configuración guardada')}
  return <section className="panel"><div className="panel-head"><div><h2>Configuración del negocio</h2><p>Datos visibles en los tickets de 80 mm.</p></div><span className="pill">Rol: {profile?.rol}</span></div><div className="form-grid"><input value={f.nombre||''} onChange={e=>setF({...f,nombre:e.target.value})}/><input placeholder="NIT" value={f.nit||''} onChange={e=>setF({...f,nit:e.target.value})}/><input placeholder="Teléfono" value={f.telefono||''} onChange={e=>setF({...f,telefono:e.target.value})}/><input placeholder="Dirección" value={f.direccion||''} onChange={e=>setF({...f,direccion:e.target.value})}/><input placeholder="Ciudad" value={f.ciudad||''} onChange={e=>setF({...f,ciudad:e.target.value})}/><input type="number" value={f.ancho_ticket_mm} readOnly/><textarea placeholder="Mensaje del ticket" value={f.mensaje_ticket||''} onChange={e=>setF({...f,mensaje_ticket:e.target.value})}/><button className="primary" onClick={save}>Guardar cambios</button></div><div className="ticket-note"><Printer/><div><b>Compatible con impresora térmica POS 80 mm</b><p>La factura usa CSS de impresión con ancho físico de 80 mm y margen interno de 3 mm. El navegador abre el diálogo de impresión y la impresora realiza el corte al terminar.</p></div></div></section>
}
